### ISSUE TITLE
Allow all ip when service type is Loadbalancer

### ISSUE THREAD

**Issue by duanhongyi** [drycc-addons/addons#32]
### The following components need to be modified

- [x] airflow/2
- [x] cloudbeaver/23
- [x] flink/1.17
- [x] fluentbit/2
- [ ] grafana/10
- [x] kafka/3.6
- [x] minio/2023
- [x] #37
- [x] opensearch/2.10
- [ ] pmm/2.41
- [x] postgresql-cluster/15
- [ ] prometheus
- [x] rabbitmq/3.12
- [x] redis-cluster/7.0
- [x] redis/7.0
- [x] seaweedfs/3
- [x] spark/3.4
- [x] zookeeper/3.9

**Comment by EamonZhang** [comment]
mysql-cluster addons fixed (#36)

**Comment by jianxiaoguo** [comment]
airflow flink kafka minio opensearch rabbitmq redis-cluster redis spark zookeeper addons fixed [](https://github.com/drycc-addons/addons/commit/286306e0ba2b8fb086fd8e78e739db5092542d6b)
fluentbit does not need modification

**Comment by jianxiaoguo** [comment]
seaweedfs [fixed](https://github.com/drycc-addons/addons/commit/fe1ef4c1aeba9794edcd7d4cddf6048ef3957773)
